### PR TITLE
C302 realtime

### PR DESCRIPTION
**Pull request by tessbianchi**
In this PR there is a lot of auto-generated .mod files from the pynml command. If you want I can make that a dependency and put it in the README or I can just keep the auto-generated code. Whichever you want.

### CODE REVIEW

**Comment by skhayrulin** [comment]
Hi @tessbianchi, thanks for your work! @slarson @pgleeson It looks like you're guys both more competent in this could you please help?

**Comment by slarson** [comment]
We've been having a look at this -- very impressive @tessbianchi -- I'm going to set up a time for all of us to chat about this.

**Comment by tessbianchi** [comment]
Great! Thank you

**Comment by tessbianchi** [comment]
Alright, I removed the .mod files... I will check out your fork @pgleeson. Let me know what you think I should do with this.

**Comment by slarson** [comment]
We met on this today ([notes here](https://docs.google.com/document/d/1DllO7eyC3v3QuJovMZptcdAGeUXNY4Dy0WU8BXNg-GY/edit#)).  @tessbianchi and I will have a look at the work Padraig is doing over at https://github.com/pgleeson/sibernetic/tree/development (especially [sibernetic_c302.py](https://github.com/pgleeson/sibernetic/blob/14f1fe3e75de5e99c2ad99272835539792014382/sibernetic_c302.py) and [main_sim.py](https://github.com/pgleeson/sibernetic/blob/14f1fe3e75de5e99c2ad99272835539792014382/src/main_sim.py), and Padraig will have another look at this pull request.  

@tessbianchi will either delete the .mod files or put them in the .gitignore.

**Comment by pgleeson** [comment]
This PR has been superseded by work which is already merged into development, so closing. 

Thanks @tessbianchi for all your work with this, it was very useful for getting c302 and Sibernetic interacting well together. If you have any more free time to work on anything related to this, please let us know.

**Pull request closed without merging**
