### PR TITLE
c302 integration fixes

### PR DESCRIPTION
**Pull request by lungd**

### CODE REVIEW

**Comment by pgleeson** [comment]
@lungd is there anything here that you think is missing from the other PR: #133?

**Comment by lungd** [comment]
I need to call setup() (of the c302 config) with data_reader='UpdatedSpreadsheetDataReader. There should be an argument for that but it is still hardcoded.
In this PR, how the 'values' list get generated inside C302NRNSimulation.run() is different.

After #133 got merged, we should think about some tests to check the values list.
I think we can close/ignore this PR, for now. I can update it, so there are only changes for the argument and the values list, if needed.

**Comment by pgleeson** [comment]
@lungd I assume it's ok to close this now. Looking at consolidating the other PRs in the next day or two...

**Comment by lungd** [comment]
Indeed. These changes are included in #138

**Pull request closed without merging**
