### PR TITLE
Video output

### PR DESCRIPTION
**Pull request by mwatts15**

### CODE REVIEW

**Comment by skhayrulin** [comment]
@mwatts15 hi, 

looking at MR, how do you think would it be useful to get this video as output? I mean that final video wan't be interactive you can not move scene scale it etc.
Maybe there is some description/discussion/issue for this feature.

**Comment by mwatts15** [comment]
Fair. This is for the OpenWorm docker container. There's a section in the
master_openworm.py script to record a video of the simulation, but it's too
finicky for me, figuring out where the window is positioned in my display
in order to use x11grab. I figured it's more straightforward to have
Sibernetic do the recording itself. You still get an interactive window
with this: this just records the GL Viewport.

If you think this needs more discussion. I can close this and open an issue.

**Comment by skhayrulin** [comment]
@mwatts15 I suppose that we can discuss this feature and figure it out how to do it more useful. E.g. we can optimize current sibernetic record mode which creating snapshots of current state of model each N steps of simulation. There is more ways make it more optimal. From the other hand I would suggest to develop a separate utility for working with such simulation records. What do you think? So I suppose to move this discussion into issue

**Comment by mwatts15** [comment]
Cool. I'll actually make an issue in the OpenWorm repo since that's where
my issue actually is. I'll make separate issues on Python configs and the
compiler warmings on Sibernetic though.

**Comment by skhayrulin** [comment]
@mwatts15 ok wait for issue put link on it when it will be ready, than continue our discussion there

**Comment by mwatts15** [comment]
@skhayrulin Here's an issue https://github.com/openworm/OpenWorm/issues/315 . I'll close this PR.

**Pull request closed without merging**
